version: '3'
services:
    mongo:
        image: mongo:latest
        container_name: ptt-mongo
        hostname: ptt-mongo
        ports:
            - "27017:27017"
        command: --wiredTigerCacheSizeGB 3

    mongo-gui:
        image: mongoclient/mongoclient
        container_name: ptt-mongo-gui
        hostname: ptt-mongo-gui
        ports:
            - "3000:3000"
        environment:
            - MONGO_URL=mongodb://ptt-mongo:27017


networks:
    default:
        external:
            name: ptt-net
